<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('menus')->insert([
            [
                'name' =>'Bakmi Keriting/Lebar Ayam Biasa Polos',
                'stock' => 20,
                'jenis' => 'Bakmi Keriting, Bakmi Lebar',
                'price' => 20000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bakmi Keriting/Lebar Ayam Jumbo Polos',
                'stock' => 20,
                'jenis' => 'Bakmi Keriting, Bakmi Lebar',
                'price' => 25000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bakmi keriting/lebar ayam + pangsit (goreng/rebus)',
                'stock' => 20,
                'jenis' => 'Bakmi Keriting, Bakmi Lebar',
                'price' => 23000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bakmi keriting/lebar ayam jumbo + pangsit (goreng/rebus)',
                'stock' => 20,
                'jenis' => 'Bakmi Keriting, Bakmi Lebar',
                'price' => 28000,
                'tenant_id'=> 1,

            ],
            [
                'name' =>'Bakmi keriting/lebar ayam + bakso',
                'stock' => 20,
                'jenis' => 'Bakmi Keriting, Bakmi Lebar',
                'price' => 25000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bakmi keriting/lebar ayam jumbo + bakso',
                'stock' => 20,
                'jenis' => 'Bakmi Keriting, Bakmi Lebar',
                'price' => 30000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bihun ayam biasa polos',
                'stock' => 20,
                'jenis' => null,
                'price' => 20000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bihun Ayam Jumbo Polos',
                'stock' => 20,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bihun ayam + pangsit (goreng/rebus)',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bihun ayam jumbo + pangsit (goreng/rebus)',
                'stock' => 20,
                'jenis' => null,
                'price' => 28000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bihun ayam + bakso',
                'stock' => 20,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 1,
            ],
            [
                'name' =>'Bihun ayam jumbo + bakso',
                'stock' => 20,
                'jenis' => null,
                'price' => 30000,
                'tenant_id'=> 1,
            ],

            [
                'name' =>'Nasi Ayam Cinta Terindah',
                'stock' => 20,
                'jenis' => null,
                'price' => 24000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Tak Terlupakan',
                'stock' => 20,
                'jenis' => null,
                'price' => 24000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Cheesy Mozza',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Sambal Geprek',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Sambal Matah',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Sambal Terasi',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Sambal Ijo',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Sambal Ikan Cakalang',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 2,
            ],
            [
                'name' =>'Nasi Ayam Cinta Sambal Roa',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 2,
            ],

            [
                'name' =>'Nasi Hainam Ayam Rebus',
                'stock' => 20,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Nasi Hainam Ayam Katsu',
                'stock' => 20,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Nasi Hainam Ayam Goreng',
                'stock' => 20,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Nasi Hainam Ayam Yakiniku',
                'stock' => 20,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Nasi Hainam Ayam Geprek',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Nasi Hainam Ayam Bakar',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Nasi Hainam Ayam Penyet',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 3,
            ],
            [
                'name' =>'Sf Bowl Sambal Matah',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 4,
            ],
            [
                'name' =>'Sf Bowl Sambal Bawang',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 4,
            ],
            [
                'name' =>'Sf Bowl Cheese Sauce',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 4,
            ],
            [
                'name' =>'Sf Bowl Spicy BBQ Sauce',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 4,
            ],
            [
                'name' =>'Sf Bowl Creamy Carbonara',
                'stock' => 20,
                'jenis' => null,
                'price' => 27000,
                'tenant_id'=> 4,
            ],

            [
                'name' =>'Paket Nasi Kuning + Ayam',
                'stock' => 30,
                'jenis' => null,
                'price' => 45000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Paket Abon Cakalang',
                'stock' => 30,
                'jenis' => null,
                'price' => 35000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Paket Ayam Rica-rica',
                'stock' => 30,
                'jenis' => null,
                'price' => 35000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Paket Cumi Woku',
                'stock' => 30,
                'jenis' => null,
                'price' => 35000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Tintuan (Bubur Manado)',
                'stock' => 30,
                'jenis' => null,
                'price' => 35000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Panada',
                'stock' => 30,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Pisang Goreng',
                'stock' => 30,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 5,
            ],
            [
                'name' =>'Perkedel Jagung',
                'stock' => 30,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 5,
            ],

            [
                'name' =>'Hainan Rice + Chicken Fillet',
                'stock' => 30,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Hainan Rice + Katsudon',
                'stock' => 30,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Hainan Rice + Steam Chicken',
                'stock' => 30,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Hainan Rice + Nauli Chicken',
                'stock' => 30,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Hainan Rice + Chicken Gepuk',
                'stock' => 30,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Fried/Steam Chicken',
                'stock' => 30,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Chicken Fillet',
                'stock' => 30,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 6,
            ],
            [
                'name' =>'Chicken Nauli',
                'stock' => 30,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 6,
            ],

            [
                'name' =>'Nasi + 2 Sayur',
                'stock' => 30,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Nasi + Telor + 2 Sayur',
                'stock' => 30,
                'jenis' => null,
                'price' => 13000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Nasi + Ayam + 2 Sayur',
                'stock' => 30,
                'jenis' => null,
                'price' => 15000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Nasi + Daging + 2 Sayur',
                'stock' => 30,
                'jenis' => null,
                'price' => 16000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Nasi + Daging + Telor + 2 Sayur',
                'stock' => 30,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Nasi + Ayam + Daging + 2 Sayur',
                'stock' => 30,
                'jenis' => null,
                'price' => 18000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Rendang',
                'stock' => 30,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 7,
            ],
            [
                'name' =>'Telor Ceplok Balado',
                'stock' => 30,
                'jenis' => null,
                'price' => 5000,
                'tenant_id'=> 7,
            ],

            [
                'name' =>'Bakso Sapi Single',
                'stock' => 30,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 8,
            ],
            [
                'name' =>'Bakso Sapi Jumbo',
                'stock' => 30,
                'jenis' => null,
                'price' => 30000,
                'tenant_id'=> 8,
            ],
            [
                'name' =>'Bakso Ayam Single',
                'stock' => 30,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 8,
            ],
            [
                'name' =>'Bakso Ayam Jumbo',
                'stock' => 30,
                'jenis' => null,
                'price' => 30000,
                'tenant_id'=> 8,
            ],
            [
                'name' =>'Bakso Ikan 3 Pcs Bihun/Kwetiaw',
                'stock' => 30,
                'jenis' => null,
                'price' => 25000,
                'tenant_id'=> 8,
            ],
            [
                'name' =>'Bakso Ikan 4 Pcs Bihun/Kwetiaw',
                'stock' => 30,
                'jenis' => null,
                'price' => 30000,
                'tenant_id'=> 8,
            ],
            [
                'name' =>'Bakso Tahu Campur',
                'stock' => 30,
                'jenis' => null,
                'price' => 30000,
                'tenant_id'=> 8,
            ],
            //Hakuya
            [
                'name' =>'Beef Rice Bowl Mayo',
                'stock' => 30,
                'jenis' => null,
                'price' => 35000,
                'tenant_id'=> 9,
            ],
            [
                'name' =>'Beef Hamburg Mayo',
                'stock' => 30,
                'jenis' => null,
                'price' => 40000,
                'tenant_id'=> 9,
            ],
            [
                'name' =>'Beef Rice Bowl Sukiyaki',
                'stock' => 30,
                'jenis' => null,
                'price' => 32000,
                'tenant_id'=> 9,
            ],
            [
                'name' =>'Beef Rice Bowl Yakiniku',
                'stock' => 30,
                'jenis' => null,
                'price' => 34000,
                'tenant_id'=> 9,
            ],
            [
                'name' =>'Chicken  Karage Rice Bowl',
                'stock' => 30,
                'jenis' => null,
                'price' => 32000,
                'tenant_id'=> 9,
            ],
            [
                'name' =>'Waffle Vanilla',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Waffle Coklat',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Waffle Stroberi',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Waffle Durian',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Waffle Keju',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Waffle Coklat Keju',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],        
            [
                'name' =>'Waffle Coklat Vanilla',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Waffle Es Krim',
                'stock' => 20,
                'jenis' => null,
                'price' => 10000,
                'tenant_id'=> 13,
            ],
            [
                'name' =>'Crepes Coklat',
                'stock' => 20,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Crepes Coklat Keju',
                'stock' => 20,
                'jenis' => null,
                'price' => 18000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Crepes Coklat Pisang',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Crepes Stroberi',
                'stock' => 20,
                'jenis' => null,
                'price' => 21000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Crepes Milo',
                'stock' => 20,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Crepes Oreo',
                'stock' => 20,
                'jenis' => null,
                'price' => 16000,
                'tenant_id'=> 14,
            ],        
            [
                'name' =>'Crepes Tiramisu',
                'stock' => 20,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Crepes Pisang',
                'stock' => 20,
                'jenis' => null,
                'price' => 21000,
                'tenant_id'=> 14,
            ],
            [
                'name' =>'Jus Jeruk',
                'stock' => 20,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 15,
            ],
            [
                'name' =>'Jus Mangga',
                'stock' => 20,
                'jenis' => null,
                'price' => 18000,
                'tenant_id'=> 15,
            ],
            [
                'name' =>'Jus Alpukat',
                'stock' => 20,
                'jenis' => null,
                'price' => 23000,
                'tenant_id'=> 15,
            ],
            [
                'name' =>'Jus Melon',
                'stock' => 20,
                'jenis' => null,
                'price' => 21000,
                'tenant_id'=> 15,
            ],
            [
                'name' =>'Jus Stroberi',
                'stock' => 20,
                'jenis' => null,
                'price' => 17000,
                'tenant_id'=> 15,
            ],
            [
                'name' =>'Jus Wortel',
                'stock' => 20,
                'jenis' => null,
                'price' => 16000,
                'tenant_id'=> 15,
            ],        
            [
                'name' =>'Jus Lemon',
                'stock' => 20,
                'jenis' => null,
                'price' => 22000,
                'tenant_id'=> 15,
            ],
            [
                'name' =>'Jus Sirsak',
                'stock' => 20,
                'jenis' => null,
                'price' => 21000,
                'tenant_id'=> 15,
            ],
        ]);
    }
}
